async function handleRequest(request) {

  const NAME = "cf-noredir"
  const html = `<!DOCTYPE html>
  <body>
    <h1>This is a page when cookie cf-noredir is present</h1>
    <p>This markup was generated by a Cloudflare Worker.</p>
  </body>`
  let reqUA = request.headers.get('user-agent')

  // Determine which group this requester is in.
  const cookie = request.headers.get("cookie")
  if (cookie && cookie.includes(`${NAME}=true`)) {
    return new Response(html, {
    headers: {
      "content-type": "text/html;charset=UTF-8",
    },
  })
  }
  else if (reqUA.match('curl'.true)) {

    let destinationURL = "https://developers.cloudflare.com/workers/about"
    return Response.redirect(destinationURL, 301)

  }
  else {
    return fetch(request)
  }
}

addEventListener("fetch", event => {
  event.respondWith(handleRequest(event.request))
})
